import type { Product, Article, Pet } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'organic-chicken-kibble',
    name: 'Organic Chicken Kibble',
    description: 'A wholesome, delicious meal crafted with cage-free chicken and whole-grain rice to support your dog\'s energy levels and digestive health. Free from artificial preservatives and fillers.',
    price: 59.99,
    brand: 'Paw & Co. Naturals',
    category: 'food',
    petType: ['dog'],
    lifeStage: ['adult', 'senior'],
    perfectFor: ['Senior Dogs', 'Picky Eaters', 'Sensitive Stomachs'],
    imageId: 'product-organic-kibble',
    images: ['product-main-image', 'product-thumb-1', 'product-thumb-2', 'product-thumb-3'],
    healthBenefit: ['skin'],
  },
  {
    id: '2',
    slug: 'tough-chew-rope-toy',
    name: 'ToughChew Rope Toy',
    description: 'Built for tough chewers, this rope toy helps clean teeth and massage gums while providing hours of fun.',
    price: 14.99,
    brand: 'ChewGuard',
    category: 'toys',
    petType: ['dog'],
    lifeStage: ['puppy', 'adult'],
    perfectFor: ['Active Dogs', 'For Puppies', 'For Pets with Dental Issues'],
    imageId: 'product-chew-toy',
    images: ['product-chew-toy'],
    healthBenefit: ['dental'],
  },
  {
    id: '3',
    slug: 'artisan-leather-collar',
    name: 'Artisan Leather Collar',
    description: 'A stylish and durable collar made from genuine leather, featuring solid brass hardware for a classic look.',
    price: 29.99,
    brand: 'Leathertail',
    category: 'supplies',
    petType: ['dog'],
    lifeStage: ['adult', 'senior'],
    perfectFor: ['For Large Breeds', 'For Small Breeds'],
    imageId: 'product-leather-collar',
    images: ['product-leather-collar'],
  },
  {
    id: '4',
    slug: 'plush-calming-cat-bed',
    name: 'Plush Calming Cat Bed',
    description: 'An ultra-soft, self-warming bed designed to soothe anxiety and provide a comfortable, secure place for your cat to rest.',
    price: 45.00,
    brand: 'ComfyCat',
    category: 'supplies',
    petType: ['cat'],
    lifeStage: ['kitten', 'adult', 'senior'],
    perfectFor: ['For Anxious Pets', 'For Senior Cats', 'For Indoor Cats'],
    imageId: 'product-cat-bed',
    images: ['product-cat-bed'],
    healthBenefit: ['anxiety'],
  },
  {
    id: '5',
    slug: 'grain-free-salmon-recipe',
    name: 'Grain-Free Salmon Recipe',
    description: 'Rich in omega fatty acids, this grain-free formula with real salmon is perfect for cats with sensitive skin or allergies.',
    price: 64.99,
    brand: 'OceanFeast',
    category: 'food',
    petType: ['cat'],
    lifeStage: ['adult', 'senior'],
    specialDiet: ['grain-free', 'limited-ingredient'],
    perfectFor: ['For Pets with Allergies', 'For Picky Eaters'],
    imageId: 'related-product-1',
    images: ['related-product-1'],
    healthBenefit: ['skin'],
  },
  {
    id: '6',
    slug: 'orthopedic-pet-bed',
    name: 'Cozy Orthopedic Pet Bed',
    description: 'A supportive memory foam bed that relieves pressure on joints, ideal for senior pets or large breeds.',
    price: 89.99,
    brand: 'SupportPaw',
    category: 'supplies',
    petType: ['dog'],
    lifeStage: ['senior'],
    perfectFor: ['For Senior Dogs', 'For Pets with Joint Pain', 'For Large Breeds'],
    imageId: 'related-product-3',
    images: ['related-product-3'],
    healthBenefit: ['joint'],
  },
  {
    id: '7',
    slug: 'all-natural-dental-chews',
    name: 'All-Natural Dental Chews',
    description: 'These tasty chews help reduce plaque and tartar build-up, promoting fresh breath and healthy gums.',
    price: 19.99,
    brand: 'BrightSmile',
    category: 'food',
    petType: ['dog'],
    lifeStage: ['adult'],
    perfectFor: ['For Pets with Dental Issues'],
    imageId: 'related-product-4',
    images: ['related-product-4'],
    healthBenefit: ['dental'],
  },
    {
    id: '8',
    slug: 'interactive-feather-wand',
    name: 'Interactive Feather Wand',
    description: 'Engage your cat\'s natural hunting instincts with this exciting feather wand, perfect for interactive play sessions.',
    price: 9.99,
    brand: 'PlayfulPet',
    category: 'toys',
    petType: ['cat'],
    lifeStage: ['kitten', 'adult'],
    perfectFor: ['For Indoor Cats', 'For Active Cats'],
    imageId: 'blog-cat-toy',
    images: ['blog-cat-toy'],
  }
];

export const articles: Article[] = [
    {
        id: '1',
        slug: 'welcoming-a-new-puppy',
        title: 'Welcoming a New Puppy: Your First-Week Checklist',
        excerpt: 'Prepare for your new furry friend with this essential guide to the first seven days.',
        category: 'New Pet Guides',
        imageId: 'blog-puppy',
        author: 'Dr. Jane Smith',
        date: '2024-07-15'
    },
    {
        id: '2',
        slug: 'top-10-enrichment-toys-for-cats',
        title: 'Top 10 Enrichment Toys to Keep Your Cat Engaged',
        excerpt: 'Discover toys that stimulate your cat\'s mind and body, preventing boredom and encouraging play.',
        category: 'Toys & Enrichment',
        imageId: 'blog-cat-toy',
        author: 'Alex Chen',
        date: '2024-07-12'
    },
    {
        id: '3',
        slug: 'pet-dental-health-guide',
        title: 'Everything You Need to Know About Pet Dental Health',
        excerpt: 'Learn the best practices for keeping your pet\'s smile bright and their gums healthy.',
        category: 'Health',
        imageId: 'blog-dental',
        author: 'Dr. Jane Smith',
        date: '2024-07-10'
    },
    {
        id: '4',
        slug: 'switching-dog-food-safely',
        title: 'A Step-by-Step Guide to Safely Switching Your Dog\'s Food',
        excerpt: 'Avoid tummy troubles with our expert tips for a smooth transition to a new diet.',
        category: 'Nutrition',
        imageId: 'blog-food-switch',
        author: 'Maria Garcia',
        date: '2024-07-05'
    },
    {
        id: '5',
        slug: 'common-puppy-behaviors',
        title: '5 Common Puppy Behaviors and How to Handle Them',
        excerpt: 'From nipping to chewing, we\'ve got you covered with positive reinforcement techniques.',
        category: 'Behavior & Training',
        imageId: 'blog-puppy-behavior',
        author: 'Alex Chen',
        date: '2024-06-28'
    },
    {
        id: '6',
        slug: 'cat-body-language',
        title: 'Understanding Your Cat\'s Body Language',
        excerpt: 'Decode your feline friend\'s signals for a stronger bond and a happier home.',
        category: 'Behavior & Training',
        imageId: 'blog-cat-body-language',
        author: 'Maria Garcia',
        date: '2024-06-25'
    },
];


export const pets: Pet[] = [
    {
        id: '1',
        name: 'Buddy',
        breed: 'Golden Retriever',
        age: 5,
        weight: 75,
        allergies: 'Chicken, Dust Mites',
        imageId: 'shop-category-dogs'
    },
    {
        id: '2',
        name: 'Lucy',
        breed: 'Siamese',
        age: 8,
        weight: 10,
        allergies: 'None',
        imageId: 'shop-category-cats'
    }
]
